### ISSUE TITLE
Separate version of Next.js installed when next-piwik-pro is installed

### ISSUE THREAD

**Issue by wojtekmaj** [PiwikPRO/next-piwik-pro#11]
**Steps to reproduce:** 
- Install Next.js
- Install @piwikpro/next-piwik-pro

**Expected result:** 
@piwikpro/next-piwik-pro uses existing copy of Next.js

**Actual result:**
next-piwik-pro installs its own version of Next.js 12

**Suggested fix:**

It appears that the only reason Next.js is a dependency of @piwikpro/next-piwik-pro is this line:

https://github.com/PiwikPRO/next-piwik-pro/blob/6979862a20ac2130be715ac182edf0fe07ad612c/src/core/index.tsx#L2

Given that:
* This package is intended to be used with Next.js,
* Literally everyone using this package will have Next.js already installed,
* [Next.js 13 did not introduce any breaking changes regarding next/script](https://nextjs.org/blog/next-13#breaking-changes),

I believe it's safe to:
* Move `next` to `peerDependencies`,
* Loosen version requirements to `^11.0.0 || ^12.0.0 || ^13.0.0`, every version of Next.js supporting next/script according to its [Version History](https://nextjs.org/docs/api-reference/next/script).

**Workaround:**

With Yarn:
```
  "resolutions": {
    "@piwikpro/next-piwik-pro/next": "<your_package_version>"
  },
```

**Comment by lysy-vlc** [comment]
Already resolved. Please check the newest version
