### ISSUE TITLE
typescript error with containerId

### ISSUE THREAD

**Issue by ciruz** [PiwikPRO/next-piwik-pro#13]
This code example from here:

```javascript
<PiwikProProvider
  containerUrl={process.env.NEXT_PUBLIC_CONTAINER_URL}
  containerId={process.env.NEXT_PUBLIC_CONTAINER_ID}
>
  <Component {...pageProps} />
</PiwikProProvider>
```
(see https://github.com/PiwikPRO/next-piwik-pro#_apptsx-1 )

gives an TypeScript error, because it needs to be a `string` https://github.com/PiwikPRO/next-piwik-pro/blob/master/src/types/index.ts#L5, but the Node global is defined as `string | undefined`, see https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/globals.d.ts#L296

**Comment by kajdemuynck** [comment]
This is due to your environment variables not being type defined. To fix this, create a file (e.g. `src/@types/environment.d.ts`) with a list of all your environment variables and their types:
```
// environment.d.ts
/* eslint-disable @typescript-eslint/no-unused-vars */
namespace NodeJS {
  interface ProcessEnv extends NodeJS.ProcessEnv {
    NEXT_PUBLIC_CONTAINER_URL: string;
    NEXT_PUBLIC_CONTAINER_ID: string;
  }
}
```
Hope this helps!

**Comment by lysy-vlc** [comment]
Envs check implemented
