### ISSUE TITLE
"next" should be a peer dependency, not a dependency

### ISSUE THREAD

**Issue by michalczukm** [PiwikPRO/next-piwik-pro#17]
Currently having "next" as a dependency can result in having multiple "next" versions in the consumer app (app which utilizes the `next-piwik-pro` package). It can lead to not-building app.

I've described the details in the PR: https://github.com/PiwikPRO/next-piwik-pro/pull/16.

**Comment by wojtekmaj** [comment]
Resolved in c1f59a8477610801746eea48eeb2cd3e989b3ae1

**Comment by michalczukm** [comment]
🥳

**Comment by lysy-vlc** [comment]
Already implemented
