### ISSUE TITLE
Piwik stops working after page change on NextJS application

### ISSUE THREAD

**Issue by kiikka** [PiwikPRO/next-piwik-pro#18]
Hello,

I have a NextJS (v13.2.4) application that uses this library to add Piwik. The consent manager opens up OK on page load and we also have a separate button that opens up the dialog again if you want to change your consent.

The problem is that after changing pages the button stops working and I get the following error message in the browser console.

`Uncaught Error: Element #ppms_cm_privacy_settings_styles already exists
    at e.addStyleElement (48293c16-c4dd-4851-a69a-d94482895295.js:8:121595)
    at e.addWidgetStyles (48293c16-c4dd-4851-a69a-d94482895295.js:8:104218)
    at MutationObserver.setupNewWidget (48293c16-c4dd-4851-a69a-d94482895295.js:8:103593)`

A <style> element with that id is added to the root of the page when the provider loads, but it seems like when changing pages the element isn't reloaded and therefore it gives out the above error.

<img width="624" alt="image" src="https://github.com/PiwikPRO/next-piwik-pro/assets/94104931/5ab01c1b-7793-4b31-91ae-d2154d6f62c1">

**Comment by kiikka** [comment]
Is there anything to consider switching to the new version? Component, props etc. that need adjusting?

**Comment by lysy-vlc** [comment]
Really depends on application. Try to check out examples provided in package repo. Think it should be pretty straight forward [examples](https://github.com/PiwikPRO/next-piwik-pro/tree/master/example)

**Comment by kiikka** [comment]
This issue has been closed but it is still active. I updated to the latest version "@piwikpro/next-piwik-pro": "^3.1.1" and the same error occurs.

**Comment by kiikka** [comment]
This MIGHT have actually been caused by adding a consentForm toggle like this

`       <button
                type='button'
                className='ppms_cm_privacy_settings_button_show underline'
                id='ppms_cm_privacy_settings_button'
              >
                {t('cookie_settings')}
              </button>
`

I decided to handle the toggling using the ppms JS api and I think it work now.

`   <button
            type='button'
            className='underline'
            onClick={() => ppms?.cm?.api('openConsentForm')}
          >
            {t('cookie_settings')}
     </button>
`

**Comment by auto200** [comment]
@kiikka Could the problem be somehow reproduced in our [example app](https://github.com/PiwikPRO/next-piwik-pro/tree/master/example)? This would give us better understanding of what You want to achieve. PR would be appreciated

**Comment by kiikka** [comment]
> This MIGHT have actually been caused by adding a consentForm toggle like this
> 
> ` <button type='button' className='ppms_cm_privacy_settings_button_show underline' id='ppms_cm_privacy_settings_button' > {t('cookie_settings')} </button>`
> 
> I decided to handle the toggling using the ppms JS api and I think it work now.
> 
> ` <button type='button' className='underline' onClick={() => ppms?.cm?.api('openConsentForm')} > {t('cookie_settings')} </button>`

This solved my issue
