### ISSUE TITLE
addEcommerceItem parameters are not declared optional

### ISSUE THREAD

**Issue by raketeFlo** [PiwikPRO/next-piwik-pro#22]
Hey hey! I found an issue with the typescript declaration of the `addEcommerceItem` parameters. According to your docs only `productSKU` is required. All the others are optional. However, your typescript declaration says all of them are required:

![Screenshot 2023-11-13 at 17 29 17](https://github.com/PiwikPRO/next-piwik-pro/assets/36693992/9e079066-e6e3-427f-baa6-5366f6dc194b)

`
export declare function addEcommerceItem(productSKU: string, productName: string, productCategory: string | string[], productPrice: number, productQuantity: number): void;
`

Did I oversee something or does this has to be fixed?

Thanks.

**Comment by lysy-vlc** [comment]
Issue closed as We now use new ecommerce methods (v2) [Check the examples](https://github.com/PiwikPRO/next-piwik-pro/blob/master/example/app/eCommerce/page.tsx)
