### ISSUE TITLE
Next.js 15 upgrade

### ISSUE THREAD

**Issue by michaelasaaw** [PiwikPRO/next-piwik-pro#37]
This library blocks upgrades of next due to peer dependency settings.

pm ERR! Could not resolve dependency:
npm ERR! peer next@">=13.0.0 <15.0.0" from @piwikpro/next-piwik-pro@3.1.1

**Comment by auto200** [comment]
[@piwikpro/next-piwik-pro@3.1.2](https://github.com/PiwikPRO/next-piwik-pro/releases/tag/3.1.2) has been released. If You encounter any problems regarding nextjs 15, please create a new issue
